#!/bin/bash
#
# Unmounts an RPI image or device (sdcard)
#
# usage: rpi_umount mount_point
#
#  Copyright (c) 2012 John Lane
#  
#  MIT License
#  
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject to
#  the following conditions:
#  
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#  
#  http://www.opensource.org/licenses/mit-license.php

if [[ $(id -u ) != 0 ]]; then

    echo "Must be root"

else
    
    for device_path in $(mount | grep $1 | sort | awk '{print $1}')
    do
    
        umount $device_path
    
        device=$(basename $device_path)
    
        [[ ${device:0:4} == loop ]] && loop_device=${device_path:0:-2}
    
    done
    
    [[ -z "${loop_device}" ]] || losetup -d ${loop_device}

fi
